# Generated by Django 4.2.7 on 2023-11-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeT', '0002_userchoice_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('result', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='MBTIType',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
