# Generated by Django 4.2.7 on 2023-11-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeT', '0003_types_remove_useranswer_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
