# Generated by Django 4.2.7 on 2023-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeT', '0006_type_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='info4',
            field=models.CharField(default='default_info3', max_length=300),
        ),
        migrations.AlterField(
            model_name='type',
            name='info1',
            field=models.CharField(default='default_info1', max_length=300),
        ),
        migrations.AlterField(
            model_name='type',
            name='info2',
            field=models.CharField(default='default_info2', max_length=300),
        ),
        migrations.AlterField(
            model_name='type',
            name='info3',
            field=models.CharField(default='default_info3', max_length=300),
        ),
    ]
