# Generated by Django 4.2.7 on 2023-11-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeT', '0007_type_info4_alter_type_info1_alter_type_info2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='diary',
            field=models.FileField(null=True, upload_to='diaries/'),
        ),
    ]
