# Generated by Django 4.2.7 on 2023-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeT', '0008_type_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
