# Generated by Django 4.2.7 on 2023-12-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeT', '0009_question_question_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
